### ISSUE TITLE
Invalid license used - GPLv2 required when using node-sword-interface

### ISSUE THREAD

**Issue by tobias-klein** [glitchassassin/armorer#22]
You have created a nice program here and you are depending on [node-sword-interface](https://github.com/ezra-bible-app/node-sword-interface). node-sword-interface is licensed under the GPL version 2 (like the SWORD library) and therefore requires that software depending on it is also released under the GPL version 2 (see the [GPL v2 FAQ](https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.html#HeardOtherLicense)). Could you therefore change the license of armorer to the GPL v2, since the currently used license is not compliant when depending on a GPLv2 software.

**Comment by glitchassassin** [comment]
Hi there! Thanks for reaching out. Viral licenses like GPL v2 are incompatible with my philosophy of open source: I believe open source software ought to be free as in beer as well as free as in freedom, and GPLv2 is not that.

Therefore, I've removed this library from the project.

Cheers!
